SELECT
ORIGIN,
DEP_TIME,
DEP_DELAY,
DEST,
ARR_TIME,
ARR_DELAY,
NOTIFY_TIME
FROM
  `valak01227408.flights.simevents`
WHERE (DEP_DELAY > 15 and ORIGIN = 'SEA') or
(ARR_DELAY > 15 AND DEST = 'SEA')
ORDER by NOTIFY_TIME ASC
